### ISSUE TITLE
Exception: template in boot-reload

### ISSUE THREAD

**Issue by coyotespike** [danielsz/system-websockets#1]
After running `git clone` and `boot dev`, I got:

```
     clojure.lang.ExceptionInfo: template already refers to: #'boot.core/template in namespace: adzerk.boot-reload
    data: {:file "adzerk/boot_reload.clj", :line 1}                                              
java.lang.IllegalStateException: template already refers to: #'boot.core/template in namespace: adzerk.boot-reload
```

I don't yet know what triggers this.

**Comment by danielsz** [comment]
Oops, sorry about that.

Bumped `boot.reload` to latest version. That should fix it.

Thank you!

**Comment by coyotespike** [comment]
Thanks for being so quick on the mark! However, we now have a new and hence more interesting error. ;-)

```
 java.lang.RuntimeException: No such var: string/index-of, compiling:(cljs/source_map.clj:260:52)                                                        
             java.lang.RuntimeException: No such var: string/index-of
```

It's kind of annoying that it doesn't give me a namespace, but there it is.

**Comment by danielsz** [comment]
This error indicates that you are using a version of Clojure anterior to 1.8. 
`clojure.string/index-of` was introduced in [1.8](https://clojure.github.io/clojure/clojure.string-api.html#clojure.string/index-of). 

Please make sure you run Boot with Clojure 1.8+.

**Comment by coyotespike** [comment]
Thanks, you're completely right. I created `boot.properties` with: 

```
BOOT_CLOJURE_VERSION=1.8.0
BOOT_VERSION=2.6.0
```

And that fixed it.

Thanks for this project, I'm looking forward to incorporating Sente with System :-)
